---
- name: Test cv_container_v3
  hosts: CloudVision
  connection: local
  gather_facts: false
  collections:
    - arista.cvp
  vars:
    CONTAINERS_PROVISION_ADD_IMAGE:
        Test_container:
            configlets: []
            imageBundle: EOS-4.25.4M
            parentContainerName: Tenant

  tasks:
    - name: "Build Container topology on {{inventory_hostname}}"
      arista.cvp.cv_container_v3:
        topology: '{{CONTAINERS_PROVISION_ADD_IMAGE}}'
      register: ADD_IMAGE

    - name: "Testing Build Container"
      assert:
        that:
          - ADD_IMAGE.container_added.changed == true
          - ADD_IMAGE.container_added.container_added_count == 1
          - ADD_IMAGE.container_added.container_added_list == ["Test_container"]
          - ADD_IMAGE.container_added.success == true

    - name: "Remove Container topology on {{inventory_hostname}} in strict mode"
      arista.cvp.cv_container_v3:
        topology: '{{CONTAINERS_PROVISION_ADD_IMAGE}}'
        apply_mode: strict
        state: absent
      register: REMOVE_IMAGE

    - name: "Testing Remove Container"
      assert:
        that:
          - REMOVE_IMAGE.container_deleted.changed == true
          - REMOVE_IMAGE.container_deleted.container_deleted_count == 1
          - REMOVE_IMAGE.container_deleted.container_deleted_list == ["Test_container"]
          - REMOVE_IMAGE.container_deleted.success == true
