---
- name: Test cv_task_v3
  hosts: CloudVision
  connection: local
  gather_facts: false
  collections:
    - arista.cvp
    
  vars:
    CVP_DEVICES_MOVE_DEVICE_EXECUTE:
      - fqdn: leaf1
        parentContainerName: "Spine"
    
    CVP_DEVICES_MOVE_DEVICE_CANCEL:
      - fqdn: leaf2
        parentContainerName: "Spine"

  tasks:
    # Running move_device to create task list
    - name: Run CV_DEVICE_V3 To Move Device For Execute Task
      arista.cvp.cv_device_v3:
          devices: '{{CVP_DEVICES_MOVE_DEVICE_EXECUTE}}'
          state: present
      register: MOVE_DEVICE_DATA_EXECUTE

    - name: Execute Task
      arista.cvp.cv_task_v3:
        tasks:
          - "{{MOVE_DEVICE_DATA_EXECUTE.devices_moved.taskIds[0]}}"
      register: EXECUTE_TASK_DATA

    - name: Testing Execute Task
      assert:
        that:
          - EXECUTE_TASK_DATA.actions_manager.changed == true
          - EXECUTE_TASK_DATA.actions_manager.actions_manager_count == 1
          - EXECUTE_TASK_DATA.actions_manager.success == true

    - name: Run CV_DEVICE_V3 To Move Device For Cancel Task
      arista.cvp.cv_device_v3:
          devices: '{{CVP_DEVICES_MOVE_DEVICE_CANCEL}}'
          state: present
      register: MOVE_DEVICE_DATA_CANCEL

    - name: Cancel Pending Tasks
      arista.cvp.cv_task_v3:
        tasks: "{{MOVE_DEVICE_DATA_CANCEL.devices_moved.taskIds[0]}}"
        state: cancelled
      register: CANCEL_TASK_DATA

    - name: Testing Cancel Task
      assert:
        that:
          - CANCEL_TASK_DATA.actions_manager.changed == true
          - CANCEL_TASK_DATA.actions_manager.actions_manager_count == 1
          - CANCEL_TASK_DATA.actions_manager.success == true
