---
- name: Test cv_tag_v3
  hosts: CloudVision
  connection: local
  gather_facts: no
  vars:
    ASSIGN_TAGS_AUTO_CREATE:
      - device: leaf1.atd.lab
        device_tags:
          - name: leaf1DAutoAssign
            value: leaf1DAutoAssign
      - device: leaf2.atd.lab
        device_tags:
          - name: leaf2DAutoAssign
            value: leaf2DAutoAssign

    CREATE_TAGS:
      - device_tags:
          - name: leaf1DCreate_New
            value: leaf1DCreate_New
          - name: leaf2DCreate_New
            value: leaf2DCreate_New

    ASSIGN_UNASSIGN_EXISTING_TAGS:
      - device: leaf1.atd.lab
        device_tags:
          - name: leaf1DCreate_New
            value: leaf1DCreate_New
      - device: leaf2.atd.lab
        device_tags:
          - name: leaf2DCreate_New
            value: leaf2DCreate_New    

    DELETE_TAGS:
      - device_tags:
          - name: leaf1DAutoAssign
            value: leaf1DAutoAssign
          - name: leaf2DAutoAssign
            value: leaf2DAutoAssign
          - name: leaf1DCreate_New
            value: leaf1DCreate_New
          - name: leaf2DCreate_New
            value: leaf2DCreate_New
    
  tasks:
    - name: Assign non-existing device tags
      arista.cvp.cv_tag_v3:
        tags: "{{ASSIGN_TAGS_AUTO_CREATE}}"
        mode: assign
        auto_create: true
      register: AUTO_CREATE_ASSIGN_TAGS

    - name: Check assign non-existing device tags
      assert:
        that:
          - AUTO_CREATE_ASSIGN_TAGS.changed == true
          - AUTO_CREATE_ASSIGN_TAGS.failed == false
          - AUTO_CREATE_ASSIGN_TAGS.success == true
          - AUTO_CREATE_ASSIGN_TAGS.tags_manager.tags_manager_list != []
          - AUTO_CREATE_ASSIGN_TAGS.tags_manager.tags_manager_count == 1

    - name: Create device tags
      arista.cvp.cv_tag_v3:
        tags: "{{CREATE_TAGS}}"
        mode: create
      register: TAGS_CREATE

    - name: Check create device tags
      assert:
        that:
          - TAGS_CREATE.changed == true
          - TAGS_CREATE.failed == false
          - TAGS_CREATE.success == true
          - TAGS_CREATE.tags_manager.tags_manager_list != []
          - TAGS_CREATE.tags_manager.tags_manager_count == 1
    
    - name: Assign existing device tags
      arista.cvp.cv_tag_v3:
        tags: "{{ASSIGN_UNASSIGN_EXISTING_TAGS}}"
        mode: assign
      register: ASSIGN_EXISTING

    - name: Check assign existing device tags
      assert:
        that:
          - ASSIGN_EXISTING.changed == true
          - ASSIGN_EXISTING.failed == false
          - ASSIGN_EXISTING.success == true
          - ASSIGN_EXISTING.tags_manager.tags_manager_list != []
          - ASSIGN_EXISTING.tags_manager.tags_manager_count == 1

    - name: Unassign existing device tags
      arista.cvp.cv_tag_v3:
        tags: "{{ASSIGN_UNASSIGN_EXISTING_TAGS}}"
        mode: unassign
      register: UNASSIGN_EXISTING

    - name: Check unassign existing device tags
      assert:
        that:
          - UNASSIGN_EXISTING.changed == true
          - UNASSIGN_EXISTING.failed == false
          - UNASSIGN_EXISTING.success == true
          - UNASSIGN_EXISTING.tags_manager.tags_manager_list != []
          - UNASSIGN_EXISTING.tags_manager.tags_manager_count == 1

    - name: Delete device tags
      arista.cvp.cv_tag_v3:
        tags: "{{DELETE_TAGS}}"
        mode: delete
      register: TAGS_DELETE

    - name: Check delete device tags
      assert:
        that:
          - TAGS_DELETE.changed == true
          - TAGS_DELETE.failed == false
          - TAGS_DELETE.success == true
          - TAGS_DELETE.tags_manager.tags_manager_list != []
          - TAGS_DELETE.tags_manager.tags_manager_count == 1

    - name: print
      debug:
        msg: "{{TAGS_DELETE}}"
